const zscan_database  = require('../../config/db.js')
const formataData = require('../../utils/formatDate.js')

async function migrationModeloIkap(result, i){
        await zscan_database.query({
            query: `insert into tb_tplt (tplt_name,tplt_ftst,tplt_ftsz,tplt_ffst,tplt_ffsz,tplt_algn,tplt_ortn,tplt_size,tplt_mtop,tplt_mrgt,tplt_mbtm,tplt_mlft,tplt_stit,tplt_spid,tplt_sptt,tplt_spdc,tplt_spbd,tplt_spag,tplt_sptg,tplt_spta,tplt_srpi,tplt_sdoc,tplt_shlp,tplt_srqt,tplt_sasn,tplt_tchn,tplt_anth,tplt_seqp,tplt_sdat,tplt_sdex,tplt_sdrr,tplt_sels,tplt_sdgn,tplt_shde,tplt_shpf,tplt_shri,tplt_rinm,tplt_ssgn,tplt_scsg,tplt_sstx,tplt_slbi,tplt_hsec,tplt_fsec,tplt_limg,tplt_linf,tplt_amnt,tplt_lang,tplt_ucrt,tplt_uchd,tplt_udlt,tplt_dhcr,tplt_dhcg,tplt_dhdl) values (
                :tplt_name,
                :tplt_ftst,
                :tplt_ftsz,
                :tplt_ffst,
                :tplt_ffsz,
                :tplt_algn,
                :tplt_ortn,
                :tplt_size,
                :tplt_mtop,
                :tplt_mrgt,
                :tplt_mbtm,
                :tplt_mlft,
                :tplt_stit,
                :tplt_spid,
                :tplt_sptt,
                :tplt_spdc,
                :tplt_spbd,
                :tplt_spag,
                :tplt_sptg,
                :tplt_spta,
                :tplt_srpi,
                :tplt_sdoc,
                :tplt_shlp,
                :tplt_srqt,
                :tplt_sasn,
                :tplt_tchn,
                :tplt_anth,
                :tplt_seqp,
                :tplt_sdat,
                :tplt_sdex,
                :tplt_sdrr,
                :tplt_sels,
                :tplt_sdgn,
                :tplt_shde,
                :tplt_shpf,
                :tplt_shri,
                :tplt_rinm,
                :tplt_ssgn,
                :tplt_scsg,
                :tplt_sstx,
                :tplt_slbi,
                :tplt_hsec,
                :tplt_fsec,
                :tplt_limg,
                :tplt_linf,
                :tplt_amnt,
                :tplt_lang,
                :tplt_ucrt,
                :tplt_uchd,
                :tplt_udlt,
                :tplt_dhcr,
                :tplt_dhcg,
                :tplt_dhdl
            );`,
            values: {
                tplt_name: result.nome ? result.nome + ' Ikap' : 'Generic Ikap',
                tplt_ftst: 'Arial',
                tplt_ftsz: 2,
                tplt_ffst: 'Arial',
                tplt_ffsz: 2,
                tplt_algn: 'left',
                tplt_ortn: 'P',
                tplt_size: 'A4',
                tplt_mtop: result.margem_sup ? result.margem_sup / 10 : 1,
                tplt_mrgt: result.margem_dir ? result.margem_dir / 10 : 1,
                tplt_mbtm: result.margem_inf ? result.margem_inf / 10 : 1,
                tplt_mlft: result.margem_esq ? result.margem_esq / 10 : 1,
                tplt_stit: 1,
                tplt_spid: 0,
                tplt_sptt: 1,
                tplt_spdc: 0,
                tplt_spbd: 1,
                tplt_spag: 1,
                tplt_sptg: 1,
                tplt_spta: 1,
                tplt_srpi: 1,
                tplt_sdoc: 0,
                tplt_shlp: 0,
                tplt_srqt: 1,
                tplt_sasn: 0,
                tplt_tchn: 0,
                tplt_anth: 0,
                tplt_seqp: 0,
                tplt_sdat: 1,
                tplt_sdex: 0,
                tplt_sdrr: 0,
                tplt_sels: 0,
                tplt_sdgn: 1,
                tplt_shde: 1,
                tplt_shpf: 0,
                tplt_shri: 0,
                tplt_rinm: '',
                tplt_ssgn: 0,
                tplt_scsg: 1,
                tplt_sstx: 0,
                tplt_slbi: 1,
                tplt_hsec: 1,
                tplt_fsec: 2,
                tplt_limg: 12,
                tplt_linf: null,
                tplt_amnt: 3,
                tplt_lang: 'PT-BR',
                tplt_ucrt: 1,
                tplt_uchd: null,
                tplt_udlt: null,
                tplt_dhcr: result.ultima_alteracao ? formataData(result.ultima_alteracao) : formataData(new Date()),
                tplt_dhcg: result.ultima_alteracao ? formataData(result.ultima_alteracao) : formataData(new Date()),
                tplt_dhdl: null

            }
        });
};

module.exports = migrationModeloIkap